---
on:
  push:
    branches:
      - dev
      - issue-3/feature/pipeline-container-linting

jobs:
  ci:
    name: CI
    uses: ./.github/workflows/ci-container.yml
  cd:
    name: CD
    uses: ./.github/workflows/cd-container.yml
    needs: ci
    with:
      container-tags: latest-dev
      platforms: linux/arm64,linux/amd64
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
