---
on:
  push:
    branches:
      - dev

jobs:
  ci:
    name: CI
    uses: DarylStark/slough-gha-wf-container-projects/.github/workflows/ci-container.yml@issue-1/feature/create-workflows
  cd:
    name: CD
    uses: DarylStark/slough-gha-wf-container-projects/.github/workflows/cd-container.yml@issue-1/feature/create-workflows
    needs: ci
    with:
      container-tags: slough-dev-dc-python:latest-dev
      platforms: linux/arm64,linux/amd64
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
