---
name: Push code (dev)
run-name: "Coding branch (dev)"
on:
  push:
    branches:
      - dev

jobs:
  ci-lint:
    name: Lint container file
    uses: ./.github/workflows/ci-container-lint.yml
  cd-deploy:
    name: Deploy container image
    runs-on: ubuntu-latest
    needs: ci-lint
    steps:
      - name: Deploy
        run: echo "Deploying container image"
