---
name: Push code (dev)
run-name: "Coding branch (dev)"
on:
  push:
    branches:
      - dev
      - issue-3/feature/pipeline-container-linting

jobs:
  ci-lint:
    name: Lint container file
    uses: ./.github/workflows/ci-container-lint.yml
  cd-deploy:
    name: Deploy container image
    uses: ./.github/workflows/cd-container-publish.yml
    with:
      container-tags: latest-dev
      platforms: linux/arm64,linux/amd64
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
